CREATE TABLE IF NOT EXISTS `formECARES` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `demographic_no` int(11),
  `provider_no` varchar(11),
  `formCreated` datetime,
  `formEdited` timestamp,
  `formData` blob,
  `completed` tinyint(1),
  `completedDate` datetime,
  PRIMARY KEY (`id`)
);
INSERT INTO `encounterForm`(`form_name`, `form_value`, `form_table`, `hidden`) VALUES ('eFI-CGA(Frailty Index)', '../formeCARES.do?method=fetch&demographicNo=', 'formECARES', 0);
INSERT INTO `measurementType`(`type`, `typeDisplayName`, `typeDescription`, `measuringInstruction`, `validation`, `createDate`) VALUES ('EFI', 'Electronic Frailty Index score', 'Frailty index score generated by the eFI-CGA Frailty Index assessment form', 'Non-frail 0 to lt0.1 Vulnerable gt0.1 to 0.2 Mild gt0.2 to lt0.3 Moderate gt0.3 or to lt0.4 Severe gt0.4 or to lt0.5 Extreme Over 0.5', '11', '2020-02-05 16:46:18');