#!/usr/bin/env sh

for arg in "$@"; do
  case $arg in
    clean)
      mvn clean
      rm -rf /usr/local/tomcat/webapps/oscar
      ;;

    install)
      # Stop the Catalina server.
      server stop

      # Build the project.
      mvn prepare-package war:exploded

      # Create a symlink from the exploded WAR directory to the Tomcat webapps directory.
      pom_file="pom.xml"
      version=$(grep -oPm 1 '<version>\K[^<]+' "$pom_file")
      snapshot_src_dir='oscar-'$version
      snapshot_dest_dir='oscar'
      if [ -d "target/$snapshot_src_dir" ] && [ ! -L "target/$snapshot_src_dir" ]; then
            mv target/$snapshot_src_dir /usr/local/tomcat/webapps/$snapshot_dest_dir
            ln -s /usr/local/tomcat/webapps/$snapshot_dest_dir target/$snapshot_src_dir
      fi

      # Start the Catalina server.
      server start
      ;;

    log)
      server log
      ;;

    *)
      mvn -Dmaven.test.skip=true prepare-package war:exploded

      pom_file="pom.xml"

      version=$(grep -oPm 1 '<version>\K[^<]+' "$pom_file")

      snapshot_src_dir='oscar-'$version
      snapshot_dest_dir='oscar'

      if [ -d "target/$snapshot_src_dir" ] && [ ! -L "target/$snapshot_src_dir" ]; then
        mv target/$snapshot_src_dir target/$snapshot_dest_dir
        ln -s $snapshot_dest_dir target/$snapshot_src_dir
      fi
      ;;
  esac
done