INSERT INTO `oscar_ephi_upgrade`.`LookupList`( `name`, `listTitle`, `description`, `categoryId`, `active`, `createdBy`, `dateCreated`) VALUES ('firstNationCommunity', 'First Nation Community', 'Full list of First Nation Communities accross Canada', NULL, 1, 'oscar', '2024-01-16 20:16:34');

SET @LOOKUPID := '';
SELECT id INTO @LOOKUPID FROM LookupList WHERE `name` = 'firstNationCommunity';

INSERT INTO `LookupListItem` (`lookupListId`, `value`, `label`, `active`) VALUES
    (@LOOKUPID,"","",1),
  (@LOOKUPID,"Akisq'nuk First Nation (BC)","Akisq'nuk First Nation (BC)",1),
  (@LOOKUPID,"aq'am (BC)","aq'am (BC)",1),
  (@LOOKUPID,"Esdilagh First Nation (BC)","Esdilagh First Nation (BC)",1),
  (@LOOKUPID,"Adams Lake (BC)","Adams Lake (BC)",1),
  (@LOOKUPID,"Ahousaht (BC)","Ahousaht (BC)",1),
  (@LOOKUPID,"Aitchelitz (BC)","Aitchelitz (BC)",1),
  (@LOOKUPID,"Ashcroft (BC)","Ashcroft (BC)",1),
  (@LOOKUPID,"Beecher Bay (BC)","Beecher Bay (BC)",1),
  (@LOOKUPID,"Binche Whut'en (BC)","Binche Whut'en (BC)",1),
  (@LOOKUPID,"Blueberry River First Nations (BC)","Blueberry River First Nations (BC)",1),
  (@LOOKUPID,"Bonaparte (BC)","Bonaparte (BC)",1),
  (@LOOKUPID,"Boothroyd (BC)","Boothroyd (BC)",1),
  (@LOOKUPID,"Boston Bar First Nation (BC)","Boston Bar First Nation (BC)",1),
  (@LOOKUPID,"Bridge River (BC)","Bridge River (BC)",1),
  (@LOOKUPID,"Burns Lake (BC)","Burns Lake (BC)",1),
  (@LOOKUPID,"Campbell River (BC)","Campbell River (BC)",1),
  (@LOOKUPID,"Canim Lake (BC)","Canim Lake (BC)",1),
  (@LOOKUPID,"Cape Mudge (BC)","Cape Mudge (BC)",1),
  (@LOOKUPID,"Cayoose Creek (BC)","Cayoose Creek (BC)",1),
  (@LOOKUPID,"Chawathil (BC)","Chawathil (BC)",1),
  (@LOOKUPID,"Cheam (BC)","Cheam (BC)",1),
  (@LOOKUPID,"Cheslatta Carrier Nation (BC)","Cheslatta Carrier Nation (BC)",1),
  (@LOOKUPID,"Coldwater (BC)","Coldwater (BC)",1),
  (@LOOKUPID,"Cook's Ferry (BC)","Cook's Ferry (BC)",1),
  (@LOOKUPID,"Cowichan (BC)","Cowichan (BC)",1),
  (@LOOKUPID,"Da'naxda'xw First Nation (BC)","Da'naxda'xw First Nation (BC)",1),
  (@LOOKUPID,"Dease River (BC)","Dease River (BC)",1),
  (@LOOKUPID,"Ditidaht (BC)","Ditidaht (BC)",1),
  (@LOOKUPID,"Doig River First Nation (BC)","Doig River First Nation (BC)",1),
  (@LOOKUPID,"Douglas (BC)","Douglas (BC)",1),
  (@LOOKUPID,"Dzawada'enuxw First Nation (BC)","Dzawada'enuxw First Nation (BC)",1),
  (@LOOKUPID,"Ehattesaht (BC)","Ehattesaht (BC)",1),
  (@LOOKUPID,"Esk'etemc (BC)","Esk'etemc (BC)",1),
  (@LOOKUPID,"Esquimalt (BC)","Esquimalt (BC)",1),
  (@LOOKUPID,"Fort Nelson First Nation (BC)","Fort Nelson First Nation (BC)",1),
  (@LOOKUPID,"Gitanmaax (BC)","Gitanmaax (BC)",1),
  (@LOOKUPID,"Gitanyow (BC)","Gitanyow (BC)",1),
  (@LOOKUPID,"Gitga'at First Nation (BC)","Gitga'at First Nation (BC)",1),
  (@LOOKUPID,"Gitsegukla (BC)","Gitsegukla (BC)",1),
  (@LOOKUPID,"Gitwangak (BC)","Gitwangak (BC)",1),
  (@LOOKUPID,"Gitxaala Nation (BC)","Gitxaala Nation (BC)",1),
  (@LOOKUPID,"Glen Vowell (BC)","Glen Vowell (BC)",1),
  (@LOOKUPID,"Gwa'Sala-Nakwaxda'xw (BC)","Gwa'Sala-Nakwaxda'xw (BC)",1),
  (@LOOKUPID,"Gwawaenuk Tribe (BC)","Gwawaenuk Tribe (BC)",1),
  (@LOOKUPID,"Hagwilget First Nation Government (BC)","Hagwilget First Nation Government (BC)",1),
  (@LOOKUPID,"Haisla Nation (BC)","Haisla Nation (BC)",1),
  (@LOOKUPID,"Halalt (BC)","Halalt (BC)",1),
  (@LOOKUPID,"Halfway River First Nation (BC)","Halfway River First Nation (BC)",1),
  (@LOOKUPID,"Heiltsuk (BC)","Heiltsuk (BC)",1),
  (@LOOKUPID,"Hesquiaht (BC)","Hesquiaht (BC)",1),
  (@LOOKUPID,"High Bar (BC)","High Bar (BC)",1),
  (@LOOKUPID,"Homalco (BC)","Homalco (BC)",1),
  (@LOOKUPID,"Hupacasath First Nation (BC)","Hupacasath First Nation (BC)",1),
  (@LOOKUPID,"Huu-ay-aht First Nations (BC)","Huu-ay-aht First Nations (BC)",1),
  (@LOOKUPID,"Iskut (BC)","Iskut (BC)",1),
  (@LOOKUPID,"K'ómoks First Nation (BC)","K'ómoks First Nation (BC)",1),
  (@LOOKUPID,"Ka:'yu:'k't'h'/Che:k:tles7et'h' First Nations (BC)","Ka:'yu:'k't'h'/Che:k:tles7et'h' First Nations (BC)",1),
  (@LOOKUPID,"Kanaka Bar (BC)","Kanaka Bar (BC)",1),
  (@LOOKUPID,"Katzie (BC)","Katzie (BC)",1),
  (@LOOKUPID,"Kispiox (BC)","Kispiox (BC)",1),
  (@LOOKUPID,"Kitasoo (BC)","Kitasoo (BC)",1),
  (@LOOKUPID,"Kitselas (BC)","Kitselas (BC)",1),
  (@LOOKUPID,"Kitsumkalum (BC)","Kitsumkalum (BC)",1),
  (@LOOKUPID,"Klahoose First Nation (BC)","Klahoose First Nation (BC)",1),
  (@LOOKUPID,"Kwadacha (BC)","Kwadacha (BC)",1),
  (@LOOKUPID,"Kwakiutl (BC)","Kwakiutl (BC)",1),
  (@LOOKUPID,"Kwantlen First Nation (BC)","Kwantlen First Nation (BC)",1),
  (@LOOKUPID,"Kwaw-kwaw-Apilt (BC)","Kwaw-kwaw-Apilt (BC)",1),
  (@LOOKUPID,"Kwiakah (BC)","Kwiakah (BC)",1),
  (@LOOKUPID,"Kwikwasut'inuxw Haxwa'mis (BC)","Kwikwasut'inuxw Haxwa'mis (BC)",1),
  (@LOOKUPID,"Kwikwetlem First Nation (BC)","Kwikwetlem First Nation (BC)",1),
  (@LOOKUPID,"Lake Babine Nation (BC)","Lake Babine Nation (BC)",1),
  (@LOOKUPID,"Lax Kw'alaams (BC)","Lax Kw'alaams (BC)",1),
  (@LOOKUPID,"Leq'á:mel First Nation (BC)","Leq'á:mel First Nation (BC)",1),
  (@LOOKUPID,"Lheidli T'enneh (BC)","Lheidli T'enneh (BC)",1),
  (@LOOKUPID,"Lhoosk'uz Dene Nation (BC)","Lhoosk'uz Dene Nation (BC)",1),
  (@LOOKUPID,"Lhtako Dene Nation (BC)","Lhtako Dene Nation (BC)",1),
  (@LOOKUPID,"Lil'wat Nation (BC)","Lil'wat Nation (BC)",1),
  (@LOOKUPID,"Little Shuswap Lake (BC)","Little Shuswap Lake (BC)",1),
  (@LOOKUPID,"Lower Kootenay (BC)","Lower Kootenay (BC)",1),
  (@LOOKUPID,"Lower Nicola (BC)","Lower Nicola (BC)",1),
  (@LOOKUPID,"Lower Similkameen (BC)","Lower Similkameen (BC)",1),
  (@LOOKUPID,"Lyackson (BC)","Lyackson (BC)",1),
  (@LOOKUPID,"Lytton (BC)","Lytton (BC)",1),
  (@LOOKUPID,"Malahat Nation (BC)","Malahat Nation (BC)",1),
  (@LOOKUPID,"Mamalilikulla First Nation (BC)","Mamalilikulla First Nation (BC)",1),
  (@LOOKUPID,"Matsqui First Nation (BC)","Matsqui First Nation (BC)",1),
  (@LOOKUPID,"McLeod Lake (BC)","McLeod Lake (BC)",1),
  (@LOOKUPID,"Metlakatla First Nation (BC)","Metlakatla First Nation (BC)",1),
  (@LOOKUPID,"Mowachaht/Muchalaht (BC)","Mowachaht/Muchalaht (BC)",1),
  (@LOOKUPID,"Musqueam (BC)","Musqueam (BC)",1),
  (@LOOKUPID,"N'Quatqua (BC)","N'Quatqua (BC)",1),
  (@LOOKUPID,"Nadleh Whuten (BC)","Nadleh Whuten (BC)",1),
  (@LOOKUPID,"Nak'azdli Whut'en (BC)","Nak'azdli Whut'en (BC)",1),
  (@LOOKUPID,"Namgis First Nation (BC)","Namgis First Nation (BC)",1),
  (@LOOKUPID,"Nanoose First Nation (BC)","Nanoose First Nation (BC)",1),
  (@LOOKUPID,"Nazko First Nation (BC)","Nazko First Nation (BC)",1),
  (@LOOKUPID,"Nee-Tahi-Buhn (BC)","Nee-Tahi-Buhn (BC)",1),
  (@LOOKUPID,"Neskonlith (BC)","Neskonlith (BC)",1),
  (@LOOKUPID,"New Westminster (BC)","New Westminster (BC)",1),
  (@LOOKUPID,"Nicomen (BC)","Nicomen (BC)",1),
  (@LOOKUPID,"Nisga'a Village of Gingolx (BC)","Nisga'a Village of Gingolx (BC)",1),
  (@LOOKUPID,"Nisga'a Village of Gitwinksihlkw (BC)","Nisga'a Village of Gitwinksihlkw (BC)",1),
  (@LOOKUPID,"Nisga'a Village of Laxgalt'sap (BC)","Nisga'a Village of Laxgalt'sap (BC)",1),
  (@LOOKUPID,"Nisga'a Village of New Aiyansh (BC)","Nisga'a Village of New Aiyansh (BC)",1),
  (@LOOKUPID,"Nooaitch (BC)","Nooaitch (BC)",1),
  (@LOOKUPID,"Nuchatlaht (BC)","Nuchatlaht (BC)",1),
  (@LOOKUPID,"Nuxalk Nation (BC)","Nuxalk Nation (BC)",1),
  (@LOOKUPID,"Okanagan (BC)","Okanagan (BC)",1),
  (@LOOKUPID,"Old Massett Village Council (BC)","Old Massett Village Council (BC)",1),
  (@LOOKUPID,"Oregon Jack Creek (BC)","Oregon Jack Creek (BC)",1),
  (@LOOKUPID,"Osoyoos (BC)","Osoyoos (BC)",1),
  (@LOOKUPID,"Pacheedaht First Nation (BC)","Pacheedaht First Nation (BC)",1),
  (@LOOKUPID,"Pauquachin (BC)","Pauquachin (BC)",1),
  (@LOOKUPID,"Penelakut Tribe (BC)","Penelakut Tribe (BC)",1),
  (@LOOKUPID,"Penticton (BC)","Penticton (BC)",1),
  (@LOOKUPID,"Peters First Nation (BC)","Peters First Nation (BC)",1),
  (@LOOKUPID,"Popkum First Nation (BC)","Popkum First Nation (BC)",1),
  (@LOOKUPID,"Prophet River First Nation (BC)","Prophet River First Nation (BC)",1),
  (@LOOKUPID,"Qualicum First Nation (BC)","Qualicum First Nation (BC)",1),
  (@LOOKUPID,"Quatsino (BC)","Quatsino (BC)",1),
  (@LOOKUPID,"Saik'uz First Nation (BC)","Saik'uz First Nation (BC)",1),
  (@LOOKUPID,"Samahquam (BC)","Samahquam (BC)",1),
  (@LOOKUPID,"Saulteau First Nations (BC)","Saulteau First Nations (BC)",1),
  (@LOOKUPID,"Seabird Island (BC)","Seabird Island (BC)",1),
  (@LOOKUPID,"Sechelt (BC)","Sechelt (BC)",1),
  (@LOOKUPID,"Semiahmoo (BC)","Semiahmoo (BC)",1),
  (@LOOKUPID,"Shackan (BC)","Shackan (BC)",1),
  (@LOOKUPID,"Shuswap (BC)","Shuswap (BC)",1),
  (@LOOKUPID,"Shxw'ow'hamel First Nation (BC)","Shxw'ow'hamel First Nation (BC)",1),
  (@LOOKUPID,"Shxwhá:y (BC)","Shxwhá:y (BC)",1),
  (@LOOKUPID,"Simpcw First Nation (BC)","Simpcw First Nation (BC)",1),
  (@LOOKUPID,"Siska (BC)","Siska (BC)",1),
  (@LOOKUPID,"Skatin Nations (BC)","Skatin Nations (BC)",1),
  (@LOOKUPID,"Skawahlook First Nation (BC)","Skawahlook First Nation (BC)",1),
  (@LOOKUPID,"Skeetchestn (BC)","Skeetchestn (BC)",1),
  (@LOOKUPID,"Skidegate (BC)","Skidegate (BC)",1),
  (@LOOKUPID,"Skin Tyee (BC)","Skin Tyee (BC)",1),
  (@LOOKUPID,"Skowkale (BC)","Skowkale (BC)",1),
  (@LOOKUPID,"Skuppah (BC)","Skuppah (BC)",1),
  (@LOOKUPID,"Skwah (BC)","Skwah (BC)",1),
  (@LOOKUPID,"Snuneymuxw First Nation (BC)","Snuneymuxw First Nation (BC)",1),
  (@LOOKUPID,"Soda Creek (BC)","Soda Creek (BC)",1),
  (@LOOKUPID,"Songhees Nation (BC)","Songhees Nation (BC)",1),
  (@LOOKUPID,"Soowahlie (BC)","Soowahlie (BC)",1),
  (@LOOKUPID,"Splatsin (BC)","Splatsin (BC)",1),
  (@LOOKUPID,"Spuzzum (BC)","Spuzzum (BC)",1),
  (@LOOKUPID,"Sq'éwlets (BC)","Sq'éwlets (BC)",1),
  (@LOOKUPID,"Squamish (BC)","Squamish (BC)",1),
  (@LOOKUPID,"Squiala First Nation (BC)","Squiala First Nation (BC)",1),
  (@LOOKUPID,"Stellat'en First Nation (BC)","Stellat'en First Nation (BC)",1),
  (@LOOKUPID,"Sts'ailes (BC)","Sts'ailes (BC)",1),
  (@LOOKUPID,"Stswecem'c Xgat'tem First Nation (BC)","Stswecem'c Xgat'tem First Nation (BC)",1),
  (@LOOKUPID,"Stz'uminus First Nation (BC)","Stz'uminus First Nation (BC)",1),
  (@LOOKUPID,"Sumas First Nation (BC)","Sumas First Nation (BC)",1),
  (@LOOKUPID,"T'it'q'et (BC)","T'it'q'et (BC)",1),
  (@LOOKUPID,"T'Sou-ke First Nation (BC)","T'Sou-ke First Nation (BC)",1),
  (@LOOKUPID,"Tahltan (BC)","Tahltan (BC)",1),
  (@LOOKUPID,"Takla Nation (BC)","Takla Nation (BC)",1),
  (@LOOKUPID,"Taku River Tlingit (BC)","Taku River Tlingit (BC)",1),
  (@LOOKUPID,"Tk'emlúps te Secwépemc (BC)","Tk'emlúps te Secwépemc (BC)",1),
  (@LOOKUPID,"Tl'azt'en Nation (BC)","Tl'azt'en Nation (BC)",1),
  (@LOOKUPID,"Tl'etinqox Government (BC)","Tl'etinqox Government (BC)",1),
  (@LOOKUPID,"Tla'amin Nation (BC)","Tla'amin Nation (BC)",1),
  (@LOOKUPID,"Tla-o-qui-aht First Nations (BC)","Tla-o-qui-aht First Nations (BC)",1),
  (@LOOKUPID,"Tlatlasikwala (BC)","Tlatlasikwala (BC)",1),
  (@LOOKUPID,"Tlowitsis Tribe (BC)","Tlowitsis Tribe (BC)",1),
  (@LOOKUPID,"Tobacco Plains (BC)","Tobacco Plains (BC)",1),
  (@LOOKUPID,"Toosey (BC)","Toosey (BC)",1),
  (@LOOKUPID,"Toquaht (BC)","Toquaht (BC)",1),
  (@LOOKUPID,"Ts'kw'aylaxw First Nation (BC)","Ts'kw'aylaxw First Nation (BC)",1),
  (@LOOKUPID,"Ts'uubaa-asatx (BC)","Ts'uubaa-asatx (BC)",1),
  (@LOOKUPID,"Tsal'alh (BC)","Tsal'alh (BC)",1),
  (@LOOKUPID,"Tsartlip (BC)","Tsartlip (BC)",1),
  (@LOOKUPID,"Tsawout First Nation (BC)","Tsawout First Nation (BC)",1),
  (@LOOKUPID,"Tsawwassen First Nation (BC)","Tsawwassen First Nation (BC)",1),
  (@LOOKUPID,"Tsay Keh Dene (BC)","Tsay Keh Dene (BC)",1),
  (@LOOKUPID,"Tseshaht (BC)","Tseshaht (BC)",1),
  (@LOOKUPID,"Tseycum (BC)","Tseycum (BC)",1),
  (@LOOKUPID,"T?ideldel First Nation (BC)","T?ideldel First Nation (BC)",1),
  (@LOOKUPID,"Tsleil-Waututh Nation (BC)","Tsleil-Waututh Nation (BC)",1),
  (@LOOKUPID,"Tzeachten (BC)","Tzeachten (BC)",1),
  (@LOOKUPID,"Uchucklesaht (BC)","Uchucklesaht (BC)",1),
  (@LOOKUPID,"Ucluelet First Nation (BC)","Ucluelet First Nation (BC)",1),
  (@LOOKUPID,"Ulkatcho (BC)","Ulkatcho (BC)",1),
  (@LOOKUPID,"Union Bar First Nation (BC)","Union Bar First Nation (BC)",1),
  (@LOOKUPID,"Upper Nicola (BC)","Upper Nicola (BC)",1),
  (@LOOKUPID,"Upper Similkameen (BC)","Upper Similkameen (BC)",1),
  (@LOOKUPID,"West Moberly First Nations (BC)","West Moberly First Nations (BC)",1),
  (@LOOKUPID,"Westbank First Nation (BC)","Westbank First Nation (BC)",1),
  (@LOOKUPID,"Wet'suwet'en First Nation (BC)","Wet'suwet'en First Nation (BC)",1),
  (@LOOKUPID,"Whispering Pines/Clinton (BC)","Whispering Pines/Clinton (BC)",1),
  (@LOOKUPID,"Williams Lake First Nation (BC)","Williams Lake First Nation (BC)",1),
  (@LOOKUPID,"Witset First Nation (BC)","Witset First Nation (BC)",1),
  (@LOOKUPID,"Wuikinuxv Nation (BC)","Wuikinuxv Nation (BC)",1),
  (@LOOKUPID,"Xaxli'p (BC)","Xaxli'p (BC)",1),
  (@LOOKUPID,"Xeni Gwet'in First Nations Government (BC)","Xeni Gwet'in First Nations Government (BC)",1),
  (@LOOKUPID,"Yakweakwioose (BC)","Yakweakwioose (BC)",1),
  (@LOOKUPID,"Yale First Nation (BC)","Yale First Nation (BC)",1),
  (@LOOKUPID,"Yekooche First Nation (BC)","Yekooche First Nation (BC)",1),
  (@LOOKUPID,"Yunesit'in Government (BC)","Yunesit'in Government (BC)",1),
  (@LOOKUPID,"Alexander (AB)","Alexander (AB)",1),
  (@LOOKUPID,"Alexis Nakota Sioux Nation (AB)","Alexis Nakota Sioux Nation (AB)",1),
  (@LOOKUPID,"Athabasca Chipewyan First Nation (AB)","Athabasca Chipewyan First Nation (AB)",1),
  (@LOOKUPID,"Bearspaw (AB)","Bearspaw (AB)",1),
  (@LOOKUPID,"Beaver First Nation (AB)","Beaver First Nation (AB)",1),
  (@LOOKUPID,"Beaver Lake Cree Nation (AB)","Beaver Lake Cree Nation (AB)",1),
  (@LOOKUPID,"Bigstone Cree Nation (AB)","Bigstone Cree Nation (AB)",1),
  (@LOOKUPID,"Blood (AB)","Blood (AB)",1),
  (@LOOKUPID,"Chiniki (AB)","Chiniki (AB)",1),
  (@LOOKUPID,"Chipewyan Prairie First Nation (AB)","Chipewyan Prairie First Nation (AB)",1),
  (@LOOKUPID,"Cold Lake First Nations (AB)","Cold Lake First Nations (AB)",1),
  (@LOOKUPID,"Dene Tha' (AB)","Dene Tha' (AB)",1),
  (@LOOKUPID,"Driftpile Cree Nation (AB)","Driftpile Cree Nation (AB)",1),
  (@LOOKUPID,"Duncan's First Nation (AB)","Duncan's First Nation (AB)",1),
  (@LOOKUPID,"Enoch Cree Nation #440 (AB)","Enoch Cree Nation #440 (AB)",1),
  (@LOOKUPID,"Ermineskin Tribe (AB)","Ermineskin Tribe (AB)",1),
  (@LOOKUPID,"Fort McKay First Nation (AB)","Fort McKay First Nation (AB)",1),
  (@LOOKUPID,"Fort McMurray #468 First Nation (AB)","Fort McMurray #468 First Nation (AB)",1),
  (@LOOKUPID,"Frog Lake (AB)","Frog Lake (AB)",1),
  (@LOOKUPID,"Heart Lake (AB)","Heart Lake (AB)",1),
  (@LOOKUPID,"Horse Lake First Nation (AB)","Horse Lake First Nation (AB)",1),
  (@LOOKUPID,"Kapawe'no First Nation (AB)","Kapawe'no First Nation (AB)",1),
  (@LOOKUPID,"Kehewin Cree Nation (AB)","Kehewin Cree Nation (AB)",1),
  (@LOOKUPID,"Little Red River Cree Nation (AB)","Little Red River Cree Nation (AB)",1),
  (@LOOKUPID,"Loon River Cree (AB)","Loon River Cree (AB)",1),
  (@LOOKUPID,"Louis Bull (AB)","Louis Bull (AB)",1),
  (@LOOKUPID,"Lubicon Lake (AB)","Lubicon Lake (AB)",1),
  (@LOOKUPID,"Mikisew Cree First Nation (AB)","Mikisew Cree First Nation (AB)",1),
  (@LOOKUPID,"Montana (AB)","Montana (AB)",1),
  (@LOOKUPID,"O'Chiese (AB)","O'Chiese (AB)",1),
  (@LOOKUPID,"Paul (AB)","Paul (AB)",1),
  (@LOOKUPID,"Peerless Trout First Nation (AB)","Peerless Trout First Nation (AB)",1),
  (@LOOKUPID,"Piikani Nation (AB)","Piikani Nation (AB)",1),
  (@LOOKUPID,"Saddle Lake Cree Nation (AB)","Saddle Lake Cree Nation (AB)",1),
  (@LOOKUPID,"Samson (AB)","Samson (AB)",1),
  (@LOOKUPID,"Sawridge First Nation (AB)","Sawridge First Nation (AB)",1),
  (@LOOKUPID,"Siksika Nation (AB)","Siksika Nation (AB)",1),
  (@LOOKUPID,"Stoney (AB)","Stoney (AB)",1),
  (@LOOKUPID,"Sturgeon Lake Cree Nation (AB)","Sturgeon Lake Cree Nation (AB)",1),
  (@LOOKUPID,"Sucker Creek (AB)","Sucker Creek (AB)",1),
  (@LOOKUPID,"Sunchild First Nation (AB)","Sunchild First Nation (AB)",1),
  (@LOOKUPID,"Swan River First Nation (AB)","Swan River First Nation (AB)",1),
  (@LOOKUPID,"Tallcree Tribal Government (AB)","Tallcree Tribal Government (AB)",1),
  (@LOOKUPID,"Tsuut'ina Nation (AB)","Tsuut'ina Nation (AB)",1),
  (@LOOKUPID,"Wesley (AB)","Wesley (AB)",1),
  (@LOOKUPID,"Whitefish Lake (AB)","Whitefish Lake (AB)",1),
  (@LOOKUPID,"Woodland Cree First Nation (AB)","Woodland Cree First Nation (AB)",1),
  (@LOOKUPID,"Barren Lands (MB)","Barren Lands (MB)",1),
  (@LOOKUPID,"Berens River (MB)","Berens River (MB)",1),
  (@LOOKUPID,"Birdtail Sioux (MB)","Birdtail Sioux (MB)",1),
  (@LOOKUPID,"Black River First Nation (MB)","Black River First Nation (MB)",1),
  (@LOOKUPID,"Bloodvein (MB)","Bloodvein (MB)",1),
  (@LOOKUPID,"Brokenhead Ojibway Nation (MB)","Brokenhead Ojibway Nation (MB)",1),
  (@LOOKUPID,"Buffalo Point First Nation (MB)","Buffalo Point First Nation (MB)",1),
  (@LOOKUPID,"Bunibonibee Cree Nation (MB)","Bunibonibee Cree Nation (MB)",1),
  (@LOOKUPID,"Canupawakpa Dakota First Nation (MB)","Canupawakpa Dakota First Nation (MB)",1),
  (@LOOKUPID,"Chemawawin Cree Nation (MB)","Chemawawin Cree Nation (MB)",1),
  (@LOOKUPID,"Cross Lake Band of Indians (MB)","Cross Lake Band of Indians (MB)",1),
  (@LOOKUPID,"Dakota Plains (MB)","Dakota Plains (MB)",1),
  (@LOOKUPID,"Dakota Tipi (MB)","Dakota Tipi (MB)",1),
  (@LOOKUPID,"Dauphin River (MB)","Dauphin River (MB)",1),
  (@LOOKUPID,"Ebb and Flow (MB)","Ebb and Flow (MB)",1),
  (@LOOKUPID,"Fisher River (MB)","Fisher River (MB)",1),
  (@LOOKUPID,"Fort Alexander (MB)","Fort Alexander (MB)",1),
  (@LOOKUPID,"Fox Lake (MB)","Fox Lake (MB)",1),
  (@LOOKUPID,"Gambler First Nation (MB)","Gambler First Nation (MB)",1),
  (@LOOKUPID,"Garden Hill First Nations (MB)","Garden Hill First Nations (MB)",1),
  (@LOOKUPID,"God's Lake First Nation (MB)","God's Lake First Nation (MB)",1),
  (@LOOKUPID,"Hollow Water (MB)","Hollow Water (MB)",1),
  (@LOOKUPID,"Keeseekoowenin (MB)","Keeseekoowenin (MB)",1),
  (@LOOKUPID,"Kinonjeoshtegon First Nation (MB)","Kinonjeoshtegon First Nation (MB)",1),
  (@LOOKUPID,"Lake Manitoba (MB)","Lake Manitoba (MB)",1),
  (@LOOKUPID,"Lake St. Martin (MB)","Lake St. Martin (MB)",1),
  (@LOOKUPID,"Little Grand Rapids (MB)","Little Grand Rapids (MB)",1),
  (@LOOKUPID,"Little Saskatchewan (MB)","Little Saskatchewan (MB)",1),
  (@LOOKUPID,"Long Plain (MB)","Long Plain (MB)",1),
  (@LOOKUPID,"Manto Sipi Cree Nation (MB)","Manto Sipi Cree Nation (MB)",1),
  (@LOOKUPID,"Marcel Colomb First Nation (MB)","Marcel Colomb First Nation (MB)",1),
  (@LOOKUPID,"Mathias Colomb (MB)","Mathias Colomb (MB)",1),
  (@LOOKUPID,"Misipawistik Cree Nation (MB)","Misipawistik Cree Nation (MB)",1),
  (@LOOKUPID,"Mosakahiken Cree Nation (MB)","Mosakahiken Cree Nation (MB)",1),
  (@LOOKUPID,"Nisichawayasihk Cree Nation (MB)","Nisichawayasihk Cree Nation (MB)",1),
  (@LOOKUPID,"Northlands Denesuline First Nation (MB)","Northlands Denesuline First Nation (MB)",1),
  (@LOOKUPID,"Norway House Cree Nation (MB)","Norway House Cree Nation (MB)",1),
  (@LOOKUPID,"O-Chi-Chak-Ko-Sipi First Nation (MB)","O-Chi-Chak-Ko-Sipi First Nation (MB)",1),
  (@LOOKUPID,"O-Pipon-Na-Piwin Cree Nation (MB)","O-Pipon-Na-Piwin Cree Nation (MB)",1),
  (@LOOKUPID,"Opaskwayak Cree Nation (MB)","Opaskwayak Cree Nation (MB)",1),
  (@LOOKUPID,"Pauingassi First Nation (MB)","Pauingassi First Nation (MB)",1),
  (@LOOKUPID,"Peguis (MB)","Peguis (MB)",1),
  (@LOOKUPID,"Pinaymootang First Nation (MB)","Pinaymootang First Nation (MB)",1),
  (@LOOKUPID,"Pine Creek (MB)","Pine Creek (MB)",1),
  (@LOOKUPID,"Poplar River First Nation (MB)","Poplar River First Nation (MB)",1),
  (@LOOKUPID,"Red Sucker Lake (MB)","Red Sucker Lake (MB)",1),
  (@LOOKUPID,"Rolling River (MB)","Rolling River (MB)",1),
  (@LOOKUPID,"Roseau River Anishinabe First Nation Government (M","Roseau River Anishinabe First Nation Government (M",1),
  (@LOOKUPID,"Sandy Bay (MB)","Sandy Bay (MB)",1),
  (@LOOKUPID,"Sapotaweyak Cree Nation (MB)","Sapotaweyak Cree Nation (MB)",1),
  (@LOOKUPID,"Sayisi Dene First Nation (MB)","Sayisi Dene First Nation (MB)",1),
  (@LOOKUPID,"Shamattawa First Nation (MB)","Shamattawa First Nation (MB)",1),
  (@LOOKUPID,"Sioux Valley Dakota Nation (MB)","Sioux Valley Dakota Nation (MB)",1),
  (@LOOKUPID,"Skownan First Nation (MB)","Skownan First Nation (MB)",1),
  (@LOOKUPID,"St. Theresa Point (MB)","St. Theresa Point (MB)",1),
  (@LOOKUPID,"Swan Lake (MB)","Swan Lake (MB)",1),
  (@LOOKUPID,"Tataskweyak Cree Nation (MB)","Tataskweyak Cree Nation (MB)",1),
  (@LOOKUPID,"Tootinaowaziibeeng Treaty Reserve (MB)","Tootinaowaziibeeng Treaty Reserve (MB)",1),
  (@LOOKUPID,"War Lake First Nation (MB)","War Lake First Nation (MB)",1),
  (@LOOKUPID,"Wasagamack First Nation (MB)","Wasagamack First Nation (MB)",1),
  (@LOOKUPID,"Waywayseecappo First Nation Treaty Four - 1874 (MB","Waywayseecappo First Nation Treaty Four - 1874 (MB",1),
  (@LOOKUPID,"Wuskwi Sipihk First Nation (MB)","Wuskwi Sipihk First Nation (MB)",1),
  (@LOOKUPID,"York Factory First Nation (MB)","York Factory First Nation (MB)",1),
  (@LOOKUPID,"Buctouche MicMac (NB)","Buctouche MicMac (NB)",1),
  (@LOOKUPID,"Eel Ground (NB)","Eel Ground (NB)",1),
  (@LOOKUPID,"Eel River Bar First Nation (NB)","Eel River Bar First Nation (NB)",1),
  (@LOOKUPID,"Elsipogtog First Nation (NB)","Elsipogtog First Nation (NB)",1),
  (@LOOKUPID,"Esgenoopetitj First Nation (NB)","Esgenoopetitj First Nation (NB)",1),
  (@LOOKUPID,"Fort Folly (NB)","Fort Folly (NB)",1),
  (@LOOKUPID,"Indian Island (NB)","Indian Island (NB)",1),
  (@LOOKUPID,"Kingsclear (NB)","Kingsclear (NB)",1),
  (@LOOKUPID,"Madawaska Maliseet First Nation (NB)","Madawaska Maliseet First Nation (NB)",1),
  (@LOOKUPID,"Metepenagiag Mi'kmaq Nation (NB)","Metepenagiag Mi'kmaq Nation (NB)",1),
  (@LOOKUPID,"Oromocto First Nation (NB)","Oromocto First Nation (NB)",1),
  (@LOOKUPID,"Pabineau (NB)","Pabineau (NB)",1),
  (@LOOKUPID,"Saint Mary's (NB)","Saint Mary's (NB)",1),
  (@LOOKUPID,"Tobique (NB)","Tobique (NB)",1),
  (@LOOKUPID,"Woodstock (NB)","Woodstock (NB)",1),
  (@LOOKUPID,"Miawpukek (NL)","Miawpukek (NL)",1),
  (@LOOKUPID,"Mushuau Innu First Nation (NL)","Mushuau Innu First Nation (NL)",1),
  (@LOOKUPID,"Qalipu Mi'kmaq First Nation (NL)","Qalipu Mi'kmaq First Nation (NL)",1),
  (@LOOKUPID,"Sheshatshiu Innu First Nation (NL)","Sheshatshiu Innu First Nation (NL)",1),
  (@LOOKUPID,"Acadia (NS)","Acadia (NS)",1),
  (@LOOKUPID,"Annapolis Valley (NS)","Annapolis Valley (NS)",1),
  (@LOOKUPID,"Bear River (NS)","Bear River (NS)",1),
  (@LOOKUPID,"Eskasoni (NS)","Eskasoni (NS)",1),
  (@LOOKUPID,"Glooscap First Nation (NS)","Glooscap First Nation (NS)",1),
  (@LOOKUPID,"Membertou (NS)","Membertou (NS)",1),
  (@LOOKUPID,"Millbrook (NS)","Millbrook (NS)",1),
  (@LOOKUPID,"Paqtnkek Mi'kmaw Nation (NS)","Paqtnkek Mi'kmaw Nation (NS)",1),
  (@LOOKUPID,"Pictou Landing (NS)","Pictou Landing (NS)",1),
  (@LOOKUPID,"Potlotek First Nation (NS)","Potlotek First Nation (NS)",1),
  (@LOOKUPID,"SIPEKNE'KATIK (NS)","SIPEKNE'KATIK (NS)",1),
  (@LOOKUPID,"Wagmatcook (NS)","Wagmatcook (NS)",1),
  (@LOOKUPID,"We'koqma'q First Nation (NS)","We'koqma'q First Nation (NS)",1),
  (@LOOKUPID,"Acho Dene Koe First Nation (NT)","Acho Dene Koe First Nation (NT)",1),
  (@LOOKUPID,"Aklavik (NT)","Aklavik (NT)",1),
  (@LOOKUPID,"Behdzi Ahda First Nation (NT)","Behdzi Ahda First Nation (NT)",1),
  (@LOOKUPID,"Dechi Laot'i First Nations (NT)","Dechi Laot'i First Nations (NT)",1),
  (@LOOKUPID,"Deh GÃ¡h Got'ie Dene First Nation (NT)","Deh GÃ¡h Got'ie Dene First Nation (NT)",1),
  (@LOOKUPID,"Deline First Nation (NT)","Deline First Nation (NT)",1),
  (@LOOKUPID,"Deninu K'ue First Nation (NT)","Deninu K'ue First Nation (NT)",1),
  (@LOOKUPID,"Dog Rib Rae (NT)","Dog Rib Rae (NT)",1),
  (@LOOKUPID,"Fort Good Hope (NT)","Fort Good Hope (NT)",1),
  (@LOOKUPID,"Gameti First Nation (NT)","Gameti First Nation (NT)",1),
  (@LOOKUPID,"Gwichya Gwich'in (NT)","Gwichya Gwich'in (NT)",1),
  (@LOOKUPID,"Inuvik Native (NT)","Inuvik Native (NT)",1),
  (@LOOKUPID,"Jean Marie River First Nation (NT)","Jean Marie River First Nation (NT)",1),
  (@LOOKUPID,"K'atlodeeche First Nation (NT)","K'atlodeeche First Nation (NT)",1),
  (@LOOKUPID,"Ka'a'gee Tu First Nation (NT)","Ka'a'gee Tu First Nation (NT)",1),
  (@LOOKUPID,"Liidlii Kue First Nation (NT)","Liidlii Kue First Nation (NT)",1),
  (@LOOKUPID,"Lutsel K'e Dene First Nation (NT)","Lutsel K'e Dene First Nation (NT)",1),
  (@LOOKUPID,"Nahanni Butte (NT)","Nahanni Butte (NT)",1),
  (@LOOKUPID,"Pehdzeh Ki First Nation (NT)","Pehdzeh Ki First Nation (NT)",1),
  (@LOOKUPID,"Salt River First Nation #195 (NT)","Salt River First Nation #195 (NT)",1),
  (@LOOKUPID,"Sambaa K'e First Nation (NT)","Sambaa K'e First Nation (NT)",1),
  (@LOOKUPID,"Smith's Landing First Nation (NT)","Smith's Landing First Nation (NT)",1),
  (@LOOKUPID,"Teetl'it Gwich'in Band Council (NT)","Teetl'it Gwich'in Band Council (NT)",1),
  (@LOOKUPID,"Tulita Dene (NT)","Tulita Dene (NT)",1),
  (@LOOKUPID,"West Point First Nation (NT)","West Point First Nation (NT)",1),
  (@LOOKUPID,"Wha Ti First Nation (NT)","Wha Ti First Nation (NT)",1),
  (@LOOKUPID,"Yellowknives Dene First Nation (NT)","Yellowknives Dene First Nation (NT)",1),
  (@LOOKUPID,"Aamjiwnaang (ON)","Aamjiwnaang (ON)",1),
  (@LOOKUPID,"Albany (ON)","Albany (ON)",1),
  (@LOOKUPID,"Alderville First Nation (ON)","Alderville First Nation (ON)",1),
  (@LOOKUPID,"Algonquins of Pikwakanagan First Nation (ON)","Algonquins of Pikwakanagan First Nation (ON)",1),
  (@LOOKUPID,"Animakee Wa Zhing #37 (ON)","Animakee Wa Zhing #37 (ON)",1),
  (@LOOKUPID,"Animbiigoo Zaagi'igan Anishinaabek (ON)","Animbiigoo Zaagi'igan Anishinaabek (ON)",1),
  (@LOOKUPID,"Anishinabe of Wauzhushk Onigum (ON)","Anishinabe of Wauzhushk Onigum (ON)",1),
  (@LOOKUPID,"Anishnaabeg of Naongashiing (ON)","Anishnaabeg of Naongashiing (ON)",1),
  (@LOOKUPID,"Aroland (ON)","Aroland (ON)",1),
  (@LOOKUPID,"Atikameksheng Anishnawbek (ON)","Atikameksheng Anishnawbek (ON)",1),
  (@LOOKUPID,"Attawapiskat (ON)","Attawapiskat (ON)",1),
  (@LOOKUPID,"Aundeck-Omni-Kaning (ON)","Aundeck-Omni-Kaning (ON)",1),
  (@LOOKUPID,"Batchewana First Nation (ON)","Batchewana First Nation (ON)",1),
  (@LOOKUPID,"Bearskin Lake (ON)","Bearskin Lake (ON)",1),
  (@LOOKUPID,"Beausoleil (ON)","Beausoleil (ON)",1),
  (@LOOKUPID,"Big Grassy (ON)","Big Grassy (ON)",1),
  (@LOOKUPID,"Biigtigong Nishnaabeg (ON)","Biigtigong Nishnaabeg (ON)",1),
  (@LOOKUPID,"Biinjitiwaabik Zaaging Anishinaabek (ON)","Biinjitiwaabik Zaaging Anishinaabek (ON)",1),
  (@LOOKUPID,"Bingwi Neyaashi Anishinaabek (ON)","Bingwi Neyaashi Anishinaabek (ON)",1),
  (@LOOKUPID,"Brunswick House (ON)","Brunswick House (ON)",1),
  (@LOOKUPID,"Caldwell (ON)","Caldwell (ON)",1),
  (@LOOKUPID,"Cat Lake (ON)","Cat Lake (ON)",1),
  (@LOOKUPID,"Chapleau Cree First Nation (ON)","Chapleau Cree First Nation (ON)",1),
  (@LOOKUPID,"Chapleau Ojibway (ON)","Chapleau Ojibway (ON)",1),
  (@LOOKUPID,"Chippewas of Georgina Island (ON)","Chippewas of Georgina Island (ON)",1),
  (@LOOKUPID,"Chippewas of Kettle and Stony Point (ON)","Chippewas of Kettle and Stony Point (ON)",1),
  (@LOOKUPID,"Chippewas of Nawash First Nation (ON)","Chippewas of Nawash First Nation (ON)",1),
  (@LOOKUPID,"Chippewas of Rama First Nation (ON)","Chippewas of Rama First Nation (ON)",1),
  (@LOOKUPID,"Chippewas of the Thames First Nation (ON)","Chippewas of the Thames First Nation (ON)",1),
  (@LOOKUPID,"Constance Lake (ON)","Constance Lake (ON)",1),
  (@LOOKUPID,"Couchiching First Nation (ON)","Couchiching First Nation (ON)",1),
  (@LOOKUPID,"Curve Lake (ON)","Curve Lake (ON)",1),
  (@LOOKUPID,"Deer Lake (ON)","Deer Lake (ON)",1),
  (@LOOKUPID,"Dokis (ON)","Dokis (ON)",1),
  (@LOOKUPID,"Eabametoong First Nation (ON)","Eabametoong First Nation (ON)",1),
  (@LOOKUPID,"Eagle Lake (ON)","Eagle Lake (ON)",1),
  (@LOOKUPID,"Flying Post (ON)","Flying Post (ON)",1),
  (@LOOKUPID,"Fort Severn (ON)","Fort Severn (ON)",1),
  (@LOOKUPID,"Fort William (ON)","Fort William (ON)",1),
  (@LOOKUPID,"Garden River First Nation (ON)","Garden River First Nation (ON)",1),
  (@LOOKUPID,"Ginoogaming First Nation (ON)","Ginoogaming First Nation (ON)",1),
  (@LOOKUPID,"Grassy Narrows First Nation (ON)","Grassy Narrows First Nation (ON)",1),
  (@LOOKUPID,"Gull Bay (ON)","Gull Bay (ON)",1),
  (@LOOKUPID,"Henvey Inlet First Nation (ON)","Henvey Inlet First Nation (ON)",1),
  (@LOOKUPID,"Hiawatha First Nation (ON)","Hiawatha First Nation (ON)",1),
  (@LOOKUPID,"Iskatewizaagegan #39 Independent First Nation (ON)","Iskatewizaagegan #39 Independent First Nation (ON)",1),
  (@LOOKUPID,"Kasabonika Lake (ON)","Kasabonika Lake (ON)",1),
  (@LOOKUPID,"Kee-Way-Win (ON)","Kee-Way-Win (ON)",1),
  (@LOOKUPID,"Kingfisher (ON)","Kingfisher (ON)",1),
  (@LOOKUPID,"Kitchenuhmaykoosib Inninuwug (ON)","Kitchenuhmaykoosib Inninuwug (ON)",1),
  (@LOOKUPID,"Lac Des Mille Lacs (ON)","Lac Des Mille Lacs (ON)",1),
  (@LOOKUPID,"Lac La Croix (ON)","Lac La Croix (ON)",1),
  (@LOOKUPID,"Lac Seul (ON)","Lac Seul (ON)",1),
  (@LOOKUPID,"Long Lake No.58 First Nation (ON)","Long Lake No.58 First Nation (ON)",1),
  (@LOOKUPID,"M'Chigeeng First Nation (ON)","M'Chigeeng First Nation (ON)",1),
  (@LOOKUPID,"Magnetawan (ON)","Magnetawan (ON)",1),
  (@LOOKUPID,"Martin Falls (ON)","Martin Falls (ON)",1),
  (@LOOKUPID,"Matachewan (ON)","Matachewan (ON)",1),
  (@LOOKUPID,"Mattagami (ON)","Mattagami (ON)",1),
  (@LOOKUPID,"McDowell Lake (ON)","McDowell Lake (ON)",1),
  (@LOOKUPID,"Michipicoten (ON)","Michipicoten (ON)",1),
  (@LOOKUPID,"Mishkeegogamang (ON)","Mishkeegogamang (ON)",1),
  (@LOOKUPID,"Missanabie Cree (ON)","Missanabie Cree (ON)",1),
  (@LOOKUPID,"Mississauga (ON)","Mississauga (ON)",1),
  (@LOOKUPID,"Mississaugas of Scugog Island First Nation (ON)","Mississaugas of Scugog Island First Nation (ON)",1),
  (@LOOKUPID,"Mississaugas of the Credit (ON)","Mississaugas of the Credit (ON)",1),
  (@LOOKUPID,"Mitaanjigamiing First Nation (ON)","Mitaanjigamiing First Nation (ON)",1),
  (@LOOKUPID,"Mohawks of the Bay of Quinte (ON)","Mohawks of the Bay of Quinte (ON)",1),
  (@LOOKUPID,"Moose Cree First Nation (ON)","Moose Cree First Nation (ON)",1),
  (@LOOKUPID,"Moose Deer Point (ON)","Moose Deer Point (ON)",1),
  (@LOOKUPID,"Moravian of the Thames (ON)","Moravian of the Thames (ON)",1),
  (@LOOKUPID,"Munsee-Delaware Nation (ON)","Munsee-Delaware Nation (ON)",1),
  (@LOOKUPID,"Muskrat Dam Lake (ON)","Muskrat Dam Lake (ON)",1),
  (@LOOKUPID,"Naicatchewenin (ON)","Naicatchewenin (ON)",1),
  (@LOOKUPID,"Naotkamegwanning (ON)","Naotkamegwanning (ON)",1),
  (@LOOKUPID,"Neskantaga First Nation (ON)","Neskantaga First Nation (ON)",1),
  (@LOOKUPID,"Nibinamik First Nation (ON)","Nibinamik First Nation (ON)",1),
  (@LOOKUPID,"Nigigoonsiminikaaning First Nation (ON)","Nigigoonsiminikaaning First Nation (ON)",1),
  (@LOOKUPID,"Niisaachewan Anishinaabe Nation (ON)","Niisaachewan Anishinaabe Nation (ON)",1),
  (@LOOKUPID,"Nipissing First Nation (ON)","Nipissing First Nation (ON)",1),
  (@LOOKUPID,"North Caribou Lake (ON)","North Caribou Lake (ON)",1),
  (@LOOKUPID,"North Spirit Lake (ON)","North Spirit Lake (ON)",1),
  (@LOOKUPID,"Northwest Angle No.33 (ON)","Northwest Angle No.33 (ON)",1),
  (@LOOKUPID,"Ojibway Nation of Saugeen (ON)","Ojibway Nation of Saugeen (ON)",1),
  (@LOOKUPID,"Ojibways of Onigaming First Nation (ON)","Ojibways of Onigaming First Nation (ON)",1),
  (@LOOKUPID,"Oneida Nation of the Thames (ON)","Oneida Nation of the Thames (ON)",1),
  (@LOOKUPID,"Pays Plat (ON)","Pays Plat (ON)",1),
  (@LOOKUPID,"Pic Mobert (ON)","Pic Mobert (ON)",1),
  (@LOOKUPID,"Pikangikum (ON)","Pikangikum (ON)",1),
  (@LOOKUPID,"Poplar Hill (ON)","Poplar Hill (ON)",1),
  (@LOOKUPID,"Rainy River First Nations (ON)","Rainy River First Nations (ON)",1),
  (@LOOKUPID,"Red Rock (ON)","Red Rock (ON)",1),
  (@LOOKUPID,"Sachigo Lake (ON)","Sachigo Lake (ON)",1),
  (@LOOKUPID,"Sagamok Anishnawbek (ON)","Sagamok Anishnawbek (ON)",1),
  (@LOOKUPID,"Sandy Lake (ON)","Sandy Lake (ON)",1),
  (@LOOKUPID,"Saugeen (ON)","Saugeen (ON)",1),
  (@LOOKUPID,"Seine River First Nation (ON)","Seine River First Nation (ON)",1),
  (@LOOKUPID,"Serpent River (ON)","Serpent River (ON)",1),
  (@LOOKUPID,"Shawanaga First Nation (ON)","Shawanaga First Nation (ON)",1),
  (@LOOKUPID,"Sheguiandah (ON)","Sheguiandah (ON)",1),
  (@LOOKUPID,"Sheshegwaning (ON)","Sheshegwaning (ON)",1),
  (@LOOKUPID,"Shoal Lake No.40 (ON)","Shoal Lake No.40 (ON)",1),
  (@LOOKUPID,"Six Nations of the Grand River (ON)","Six Nations of the Grand River (ON)",1),
  (@LOOKUPID,"Slate Falls Nation (ON)","Slate Falls Nation (ON)",1),
  (@LOOKUPID,"Taykwa Tagamou Nation (ON)","Taykwa Tagamou Nation (ON)",1),
  (@LOOKUPID,"Temagami First Nation (ON)","Temagami First Nation (ON)",1),
  (@LOOKUPID,"Thessalon (ON)","Thessalon (ON)",1),
  (@LOOKUPID,"Wabaseemoong Independent Nations (ON)","Wabaseemoong Independent Nations (ON)",1),
  (@LOOKUPID,"Wabauskang First Nation (ON)","Wabauskang First Nation (ON)",1),
  (@LOOKUPID,"Wabigoon Lake Ojibway Nation (ON)","Wabigoon Lake Ojibway Nation (ON)",1),
  (@LOOKUPID,"Wahgoshig First Nation (ON)","Wahgoshig First Nation (ON)",1),
  (@LOOKUPID,"Wahnapitae (ON)","Wahnapitae (ON)",1),
  (@LOOKUPID,"Wahta Mohawk (ON)","Wahta Mohawk (ON)",1),
  (@LOOKUPID,"Walpole Island (ON)","Walpole Island (ON)",1),
  (@LOOKUPID,"Wapekeka (ON)","Wapekeka (ON)",1),
  (@LOOKUPID,"Wasauksing First Nation (ON)","Wasauksing First Nation (ON)",1),
  (@LOOKUPID,"Washagamis Bay (ON)","Washagamis Bay (ON)",1),
  (@LOOKUPID,"Wawakapewin (ON)","Wawakapewin (ON)",1),
  (@LOOKUPID,"Webequie (ON)","Webequie (ON)",1),
  (@LOOKUPID,"Weenusk (ON)","Weenusk (ON)",1),
  (@LOOKUPID,"Whitefish River (ON)","Whitefish River (ON)",1),
  (@LOOKUPID,"Whitesand (ON)","Whitesand (ON)",1),
  (@LOOKUPID,"Wikwemikong (ON)","Wikwemikong (ON)",1),
  (@LOOKUPID,"Wunnumin (ON)","Wunnumin (ON)",1),
  (@LOOKUPID,"Zhiibaahaasing First Nation (ON)","Zhiibaahaasing First Nation (ON)",1),
  (@LOOKUPID,"Abegweit (PE)","Abegweit (PE)",1),
  (@LOOKUPID,"Lennox Island (PE)","Lennox Island (PE)",1),
  (@LOOKUPID,"Algonquins of Barriere Lake (QC)","Algonquins of Barriere Lake (QC)",1),
  (@LOOKUPID,"Atikamekw d'Opitciwan (QC)","Atikamekw d'Opitciwan (QC)",1),
  (@LOOKUPID,"Bande des Innus de Pessamit (QC)","Bande des Innus de Pessamit (QC)",1),
  (@LOOKUPID,"Communauté anicinape de Kitcisakik (QC)","Communauté anicinape de Kitcisakik (QC)",1),
  (@LOOKUPID,"Conseil de la PremiÃ¨re Nation Abitibiwinni (QC)","Conseil de la PremiÃ¨re Nation Abitibiwinni (QC)",1),
  (@LOOKUPID,"Conseil des Atikamekw de Wemotaci (QC)","Conseil des Atikamekw de Wemotaci (QC)",1),
  (@LOOKUPID,"Cree Nation of Chisasibi (QC)","Cree Nation of Chisasibi (QC)",1),
  (@LOOKUPID,"Cree Nation of Mistissini (QC)","Cree Nation of Mistissini (QC)",1),
  (@LOOKUPID,"Cree Nation of Nemaska (QC)","Cree Nation of Nemaska (QC)",1),
  (@LOOKUPID,"Cree Nation of Wemindji (QC)","Cree Nation of Wemindji (QC)",1),
  (@LOOKUPID,"Eastmain (QC)","Eastmain (QC)",1),
  (@LOOKUPID,"Innu Takuaikan Uashat Mak Mani-Utenam (QC)","Innu Takuaikan Uashat Mak Mani-Utenam (QC)",1),
  (@LOOKUPID,"Innue Essipit (QC)","Innue Essipit (QC)",1),
  (@LOOKUPID,"Kebaowek First Nation (QC)","Kebaowek First Nation (QC)",1),
  (@LOOKUPID,"Kitigan Zibi Anishinabeg (QC)","Kitigan Zibi Anishinabeg (QC)",1),
  (@LOOKUPID,"La Nation Innu Matimekush-Lac John (QC)","La Nation Innu Matimekush-Lac John (QC)",1),
  (@LOOKUPID,"La Nation Micmac de Gespeg (QC)","La Nation Micmac de Gespeg (QC)",1),
  (@LOOKUPID,"Les Atikamekw de Manawan (QC)","Les Atikamekw de Manawan (QC)",1),
  (@LOOKUPID,"Les Innus de Ekuanitshit (QC)","Les Innus de Ekuanitshit (QC)",1),
  (@LOOKUPID,"Listuguj Mi'gmaq Government (QC)","Listuguj Mi'gmaq Government (QC)",1),
  (@LOOKUPID,"Long Point First Nation (QC)","Long Point First Nation (QC)",1),
  (@LOOKUPID,"Micmacs of Gesgapegiag (QC)","Micmacs of Gesgapegiag (QC)",1),
  (@LOOKUPID,"Mohawks of Akwesasne (QC)","Mohawks of Akwesasne (QC)",1),
  (@LOOKUPID,"Mohawks of KahnawÃ¡:ke (QC)","Mohawks of KahnawÃ¡:ke (QC)",1),
  (@LOOKUPID,"Mohawks of Kanesatake (QC)","Mohawks of Kanesatake (QC)",1),
  (@LOOKUPID,"Montagnais de Pakua Shipi (QC)","Montagnais de Pakua Shipi (QC)",1),
  (@LOOKUPID,"Montagnais de Unamen Shipu (QC)","Montagnais de Unamen Shipu (QC)",1),
  (@LOOKUPID,"Naskapi Nation of Kawawachikamach (QC)","Naskapi Nation of Kawawachikamach (QC)",1),
  (@LOOKUPID,"Nation Anishnabe du Lac Simon (QC)","Nation Anishnabe du Lac Simon (QC)",1),
  (@LOOKUPID,"Nation Huronne Wendat (QC)","Nation Huronne Wendat (QC)",1),
  (@LOOKUPID,"Odanak (QC)","Odanak (QC)",1),
  (@LOOKUPID,"Oujé-Bougoumou Cree Nation (QC)","Oujé-Bougoumou Cree Nation (QC)",1),
  (@LOOKUPID,"Première Nation de Whapmagoostui (QC)","Première Nation de Whapmagoostui (QC)",1),
  (@LOOKUPID,"Première Nation des Abénakis de Wôlinak (QC)","Première Nation des Abénakis de Wôlinak (QC)",1),
  (@LOOKUPID,"Première Nation des Innus de Nutashkuan (QC)","Première Nation des Innus de Nutashkuan (QC)",1),
  (@LOOKUPID,"Première Nation des Pekuakamiulnuatsh (QC)","Première Nation des Pekuakamiulnuatsh (QC)",1),
  (@LOOKUPID,"Première Nation Wolastoqiyik (Malecite) Wahsipekuk","Première Nation Wolastoqiyik (Malecite) Wahsipekuk",1),
  (@LOOKUPID,"The Crees of the Waskaganish First Nation (QC)","The Crees of the Waskaganish First Nation (QC)",1),
  (@LOOKUPID,"Timiskaming First Nation (QC)","Timiskaming First Nation (QC)",1),
  (@LOOKUPID,"Waswanipi (QC)","Waswanipi (QC)",1),
  (@LOOKUPID,"Wolf Lake (QC)","Wolf Lake (QC)",1),
  (@LOOKUPID,"Ahtahkakoop (SK)","Ahtahkakoop (SK)",1),
  (@LOOKUPID,"Beardy's and Okemasis (SK)","Beardy's and Okemasis (SK)",1),
  (@LOOKUPID,"Big Island Lake Cree Nation (SK)","Big Island Lake Cree Nation (SK)",1),
  (@LOOKUPID,"Big River (SK)","Big River (SK)",1),
  (@LOOKUPID,"Birch Narrows First Nation (SK)","Birch Narrows First Nation (SK)",1),
  (@LOOKUPID,"Black Lake (SK)","Black Lake (SK)",1),
  (@LOOKUPID,"Buffalo River Dene Nation (SK)","Buffalo River Dene Nation (SK)",1),
  (@LOOKUPID,"Canoe Lake Cree First Nation (SK)","Canoe Lake Cree First Nation (SK)",1),
  (@LOOKUPID,"Carry The Kettle (SK)","Carry The Kettle (SK)",1),
  (@LOOKUPID,"Clearwater River Dene (SK)","Clearwater River Dene (SK)",1),
  (@LOOKUPID,"Cote First Nation 366 (SK)","Cote First Nation 366 (SK)",1),
  (@LOOKUPID,"Cowessess (SK)","Cowessess (SK)",1),
  (@LOOKUPID,"Cumberland House Cree Nation (SK)","Cumberland House Cree Nation (SK)",1),
  (@LOOKUPID,"Day Star (SK)","Day Star (SK)",1),
  (@LOOKUPID,"English River First Nation (SK)","English River First Nation (SK)",1),
  (@LOOKUPID,"Fishing Lake First Nation (SK)","Fishing Lake First Nation (SK)",1),
  (@LOOKUPID,"Flying Dust First Nation (SK)","Flying Dust First Nation (SK)",1),
  (@LOOKUPID,"Fond du Lac (SK)","Fond du Lac (SK)",1),
  (@LOOKUPID,"George Gordon First Nation (SK)","George Gordon First Nation (SK)",1),
  (@LOOKUPID,"Hatchet Lake (SK)","Hatchet Lake (SK)",1),
  (@LOOKUPID,"James Smith (SK)","James Smith (SK)",1),
  (@LOOKUPID,"Kahkewistahaw (SK)","Kahkewistahaw (SK)",1),
  (@LOOKUPID,"Kawacatoose (SK)","Kawacatoose (SK)",1),
  (@LOOKUPID,"Keeseekoose (SK)","Keeseekoose (SK)",1),
  (@LOOKUPID,"Kinistin Saulteaux Nation (SK)","Kinistin Saulteaux Nation (SK)",1),
  (@LOOKUPID,"Lac La Ronge (SK)","Lac La Ronge (SK)",1),
  (@LOOKUPID,"Little Black Bear (SK)","Little Black Bear (SK)",1),
  (@LOOKUPID,"Little Pine (SK)","Little Pine (SK)",1),
  (@LOOKUPID,"Lucky Man (SK)","Lucky Man (SK)",1),
  (@LOOKUPID,"Makwa Sahgaiehcan First Nation (SK)","Makwa Sahgaiehcan First Nation (SK)",1),
  (@LOOKUPID,"Ministikwan Lake Cree Nation (SK)","Ministikwan Lake Cree Nation (SK)",1),
  (@LOOKUPID,"Mistawasis Nêhiyawak (SK)","Mistawasis Nêhiyawak (SK)",1),
  (@LOOKUPID,"Montreal Lake (SK)","Montreal Lake (SK)",1),
  (@LOOKUPID,"Moosomin (SK)","Moosomin (SK)",1),
  (@LOOKUPID,"Mosquito, Grizzly Bear's Head, Lean Man First Nati","Mosquito, Grizzly Bear's Head, Lean Man First Nati",1),
  (@LOOKUPID,"Muscowpetung (SK)","Muscowpetung (SK)",1),
  (@LOOKUPID,"Muskeg Lake Cree Nation #102 (SK)","Muskeg Lake Cree Nation #102 (SK)",1),
  (@LOOKUPID,"Muskoday First Nation (SK)","Muskoday First Nation (SK)",1),
  (@LOOKUPID,"Muskowekwan (SK)","Muskowekwan (SK)",1),
  (@LOOKUPID,"Nekaneet (SK)","Nekaneet (SK)",1),
  (@LOOKUPID,"Ocean Man (SK)","Ocean Man (SK)",1),
  (@LOOKUPID,"Ochapowace (SK)","Ochapowace (SK)",1),
  (@LOOKUPID,"Okanese (SK)","Okanese (SK)",1),
  (@LOOKUPID,"One Arrow First Nation (SK)","One Arrow First Nation (SK)",1),
  (@LOOKUPID,"Onion Lake Cree Nation (SK)","Onion Lake Cree Nation (SK)",1),
  (@LOOKUPID,"Pasqua First Nation #79 (SK)","Pasqua First Nation #79 (SK)",1),
  (@LOOKUPID,"Peepeekisis Cree Nation No.81 (SK)","Peepeekisis Cree Nation No.81 (SK)",1),
  (@LOOKUPID,"Pelican Lake (SK)","Pelican Lake (SK)",1),
  (@LOOKUPID,"Peter Ballantyne Cree Nation (SK)","Peter Ballantyne Cree Nation (SK)",1),
  (@LOOKUPID,"Pheasant Rump Nakota (SK)","Pheasant Rump Nakota (SK)",1),
  (@LOOKUPID,"Piapot (SK)","Piapot (SK)",1),
  (@LOOKUPID,"Poundmaker (SK)","Poundmaker (SK)",1),
  (@LOOKUPID,"Red Earth (SK)","Red Earth (SK)",1),
  (@LOOKUPID,"Red Pheasant (SK)","Red Pheasant (SK)",1),
  (@LOOKUPID,"Saulteaux (SK)","Saulteaux (SK)",1),
  (@LOOKUPID,"Shoal Lake Cree Nation (SK)","Shoal Lake Cree Nation (SK)",1),
  (@LOOKUPID,"Standing Buffalo (SK)","Standing Buffalo (SK)",1),
  (@LOOKUPID,"Star Blanket Cree Nation (SK)","Star Blanket Cree Nation (SK)",1),
  (@LOOKUPID,"Sturgeon Lake First Nation (SK)","Sturgeon Lake First Nation (SK)",1),
  (@LOOKUPID,"Sweetgrass (SK)","Sweetgrass (SK)",1),
  (@LOOKUPID,"The Key First Nation (SK)","The Key First Nation (SK)",1),
  (@LOOKUPID,"Thunderchild First Nation (SK)","Thunderchild First Nation (SK)",1),
  (@LOOKUPID,"Wahpeton Dakota Nation (SK)","Wahpeton Dakota Nation (SK)",1),
  (@LOOKUPID,"Waterhen Lake (SK)","Waterhen Lake (SK)",1),
  (@LOOKUPID,"White Bear (SK)","White Bear (SK)",1),
  (@LOOKUPID,"Whitecap Dakota First Nation (SK)","Whitecap Dakota First Nation (SK)",1),
  (@LOOKUPID,"Witchekan Lake (SK)","Witchekan Lake (SK)",1),
  (@LOOKUPID,"Wood Mountain (SK)","Wood Mountain (SK)",1),
  (@LOOKUPID,"Yellow Quill (SK)","Yellow Quill (SK)",1),
  (@LOOKUPID,"Zagime Anishinabek (SK)","Zagime Anishinabek (SK)",1),
  (@LOOKUPID,"Carcross/Tagish First Nation (YT)","Carcross/Tagish First Nation (YT)",1),
  (@LOOKUPID,"Champagne and Aishihik First Nations (YT)","Champagne and Aishihik First Nations (YT)",1),
  (@LOOKUPID,"First Nation of Nacho Nyak Dun (YT)","First Nation of Nacho Nyak Dun (YT)",1),
  (@LOOKUPID,"Kluane First Nation (YT)","Kluane First Nation (YT)",1),
  (@LOOKUPID,"Kwanlin Dun First Nation (YT)","Kwanlin Dun First Nation (YT)",1),
  (@LOOKUPID,"Liard First Nation (YT)","Liard First Nation (YT)",1),
  (@LOOKUPID,"Little Salmon/Carmacks First Nation (YT)","Little Salmon/Carmacks First Nation (YT)",1),
  (@LOOKUPID,"Ross River Dena Council (YT)","Ross River Dena Council (YT)",1),
  (@LOOKUPID,"Selkirk First Nation (YT)","Selkirk First Nation (YT)",1),
  (@LOOKUPID,"Ta'an Kwach'an (YT)","Ta'an Kwach'an (YT)",1),
  (@LOOKUPID,"Teslin Tlingit Council (YT)","Teslin Tlingit Council (YT)",1),
  (@LOOKUPID,"Tr'ondëk Hwëch'in (YT)","Tr'ondëk Hwëch'in (YT)",1),
  (@LOOKUPID,"Vuntut Gwitchin First Nation (YT)","Vuntut Gwitchin First Nation (YT)",1),
  (@LOOKUPID,"White River First Nation (YT)","White River First Nation (YT)",1);
